### ISSUE TITLE
"View page preview" button not present

### ISSUE THREAD

**Issue by davjo664** [strapi/strapi-template-corporate#1]
The "View page preview" button in the Strapi UI is not present.

![image](https://user-images.githubusercontent.com/17021515/101896530-70a05680-3ba9-11eb-877a-5a62bb6b2837.png)

**Comment by remidej** [comment]
Hello! This is unfortunately normal.

A couple of months ago, we converted this started to use our new templates system. This brought a lot of benefits, but means we could not rely on the extensions folder anymore, which was used in this demo. So we decided to remove that feature for now, and wait until our new Plugin API is released to find a cleaner solution. ([see the RFC](https://github.com/strapi/rfcs/pull/23))

In the meantime, you can still implement it yourself. Copy the extensions directory from an earlier version of the starter ([like this one](https://github.com/strapi/strapi-starter-next-corporate/tree/97d6903eab28af4a14f9f605f48a289175e36f4a/backend/extensions)), add it to your own Strapi project, run yarn build and you should be good to go.
