### ISSUE TITLE
cannot create project with create-strapi-app@4.1.2

### ISSUE THREAD

**Issue by jingkang99** [strapi/strapi-template-corporate#15]
**yarn create strapi-app sz1strapi --template https://github.com/strapi/strapi-template-corporate**

Error: ⛔️ Template installation failed: Command failed: npm view https://github.com/strapi/strapi-template-corporate name version --silent

![image](https://user-images.githubusercontent.com/10793075/156656449-c67240d8-1c62-48b2-8ccb-adebf71e8bd8.png)

**Comment by remidej** [comment]
Here are the working commands:

For Strapi v3:

```sh
yarn create strapi-app@3.6.9 sz1strapi --template https://github.com/strapi/strapi-template-corporate
```

For Strapi v4:

```sh
yarn create strapi-app sz1strapi --template corporate
```
